---

# Now using libinput
- pacman: name=xf86-input-synaptics state=absent

# Using KMS
- pacman: name=xf86-video-intel state=absent
- pacman: name=libva-intel-driver state=absent  # was never needed anyway...
- file: path=/etc/X11/xorg.conf.d/20-intel.conf state=absent
