---
- name: Install desktop minimal base (cdown specific)
  pacman:
    name:
      # VPN -- only used for FB right now
      - openconnect

      # Directly unused by Lin
      - irssi
      - mktorrent
      - python-virtualenvwrapper
      - asp
      - clipmenu
      - rclone
      - cifs-utils

      # Mail
      - mutt
      - w3m
      - msmtp

      # Photos
      - hugin
      - gimp
      - imagemagick
      - ghostscript  # imagemagick optdepends

      # Music
      - easytag

      # USB creation
      - udftools

      # Camera SD card
      - exfatprogs

      # Subtitles
      - enca

      # chrisdown.name
      - tidy

      # vipe for playlist-edit
      - moreutils

      - patchelf

- name: Install desktop minimal base (cdown specific, AUR)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes
  with_items:
    - cconv
    - sshrc
    - xinput-toggle
    - nota
    - mpdscribble
    - geteltorito
    - whatmp3
    - shellcheck-bin
    - adb-sync-git
    - matterhorn-bin
    - procmail
    - bindfs
    - dspdfviewer-git
  become: yes
  become_user: makepkg

- name: Install nomachine
  aur: name=nomachine skip_installed=yes skip_pgp_check=yes
  become: yes
  become_user: makepkg

- name: Good god, what a dumb installer
  systemd: name=nxserver state=stopped enabled=no masked=yes daemon_reload=yes
  when: systemd_init

- name: Install ImageMagick policy
  copy: src=files/policy.xml dest=/etc/ImageMagick-7/policy.xml
