---
- name: Install desktop minimal base (cdown specific)
  pacman:
    name:
      # VPN -- only used for FB right now
      - openconnect

      # Directly unused by Lin
      - pass
      - irssi
      - pdfpc
      - mktorrent
      - python-virtualenvwrapper
      - asp
      - clipmenu

      # Duply
      - python-boto

      # Mail
      - mutt
      - w3m
      - procmail
      - msmtp

      # Android, can be moved if Lin eventually uses it
      - android-tools
      - android-udev

      # Photos
      - hugin
      - gimp
      - imagemagick
      - ghostscript  # imagemagick optdepends

      # Music
      - mpd
      - mpc
      - easytag

      # USB creation
      - udftools

      # Camera SD card
      - exfatprogs

      # Subtitles
      - enca

      # Backup drive
      - veracrypt

- name: Install desktop minimal base (cdown specific, AUR)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes
  with_items:
    - cconv
    - duply
    - drive-bin
    - sshrc
    - xinput-toggle
    - nota
    - mpdscribble
    - mpdmenu
    - geteltorito
    - sxiv-photoorg-git
    - whatmp3
    - shellcheck-bin
    - dspdfviewer  # while pdfpc is being weird...
    - adb-sync-git
    - matterhorn-bin
  become: yes
  become_user: makepkg

- name: Install ImageMagick policy
  copy: src=files/policy.xml dest=/etc/ImageMagick-7/policy.xml
