---
- name: Install desktop minimal base
  pacman:
    name:
      - pass
      - mupdf
      - graphviz
      - mpv
      - qemu-desktop
      - wireguard-tools
      - firefox

      # Technically could also be used on the server, but in reality we only
      # use this on desktop for note/e-mail writing.
      - aspell
      - aspell-en

      # Screenshots
      - scrot
      - slop

      # X
      - xclip
      - redshift

      # Pinyin input
      - fcitx
      - fcitx-sunpinyin
      - fcitx-gtk3

      # Desktop environment
      - dmenu
      - rxvt-unicode
      - libnotify
      - dunst
      - urxvt-perls

      # Reevaluate later
      - syncplay

      # Android
      - android-tools
      - android-udev

      # Music
      - mpd
      - mpd-mpris
      - mpc
      - playerctl


- name: Install desktop minimal base (AUR)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes
  with_items:
    - dwm-layoutconfigrules-git
    - st-xres-git
    - pngquant
    - google-chrome
    - downgrade
    - psi-notify
    - xob
    - bats-battery
    - sxiv-photoorg-git
    - mpdmenu
    - physlock
  become: yes
  become_user: makepkg

- name: Install lockphyslock
  copy: src=files/bin/lockphyslock dest=/usr/local/bin/lockphyslock mode=755
