---
- name: Install desktop minimal base
  pacman:
    name:
      - mupdf
      - graphviz
      - mpv

      # Technically could also be used on the server, but in reality we only
      # use this on desktop for note/e-mail writing.
      - aspell
      - aspell-en

      # We just use dhcpcd directly on servers
      - netctl
      - wpa_supplicant
      - dialog  # optdepends for wifi-menu

      # Screenshots
      - maim
      - slop

      # X
      - xclip
      - redshift

      # Pinyin input
      - fcitx
      - fcitx-sunpinyin
      - fcitx-gtk3

      # Desktop environment
      - dmenu
      - rxvt-unicode
      - physlock
      - libnotify
      - dunst
      - urxvt-perls

      # Reevaluate later
      - syncplay

- name: Install desktop minimal base (AUR)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes
  with_items:
    - dwm-layoutconfigrules-git
    - pngquant
    - google-chrome
    - downgrade
    - psi-notify
    - xob
    - bats
  become: yes
  become_user: makepkg

- name: Install lockphyslock
  copy: src=files/bin/lockphyslock dest=/usr/local/bin/lockphyslock mode=755
