---
- name: Add local users to wheel group to be able to access CUPS
  user: name={{ item }} groups=wheel append=yes
  with_items: '{{ users }}'

- pacman: name=avahi
- pacman: name=cups
- pacman: name=nss-mdns       # for .local resolution
- pacman: name=hplip          # for hp drivers
- pacman: name=python-pillow  # for scanning support with hp-scan

- systemd: name=avahi-daemon state=started enabled=yes daemon_reload=yes
- systemd: name=cups state=started enabled=yes daemon_reload=yes

# New printers can be added at localhost:631/admin -> find new printers
