#!/bin/bash -e

# https://bit.ly/2omT14e

(( DEBUG )) && set -x

if ! (( USE_CURRENT_CHECKOUT )); then
    pacman -S --noconfirm git ansible python

    playbook_dir=$(mktemp -ud)
    trap 'cd /; rm -rf "$playbook_dir"' 0

    git clone --recursive git://github.com/cdown/ansible-server.git \
        "$playbook_dir"

    # set -e is already set, so...
    # shellcheck disable=SC2164
    cd "$playbook_dir"
fi

ansible-playbook -i localhost, -v setup.yml
