#!/bin/bash -e

(( UID )) && exec sudo "$0" "$@"

config_file=/.ansibleconfig
type_file=/.ansibletype

if ! [[ -e $config_file ]]; then
    read -r -p 'Config: ' AS_CONFIG
    echo "$AS_CONFIG" > "$config_file"
fi

AS_CONFIG=$(cat "$config_file")
export AS_CONFIG

ansible-playbook -c local -i localhost, "$@" "${0%/*}"/setup.yml
