---
- hosts: localhost
  connection: local

  vars:
    kernel: linux-lts
    default_kernel_params: 'cgroup_no_v1=all audit=0 swiotlb=4096'
    extra_kernel_params: ''
    hdd_scheduler: mq-deadline
    ssd_scheduler: mq-deadline
    boot_mode: uefi
    root_on_ssd: true
    remote_server: false
    compile_server: false
    desktop: false
    cdown: true
    game_server: false
    users:
      - cdown

  vars_files:
    - "vars/{{ lookup('env', 'AS_CONFIG') }}.yml"

  tasks:

    # Base: things wanted no matter what config is used

    - include_tasks: tasks/base/locale.yml
    - include_tasks: tasks/base/pacman.yml
    - include_tasks: tasks/base/sysctl.yml
    - include_tasks: tasks/base/sudo.yml
    - include_tasks: tasks/base/aur.yml
    - include_tasks: tasks/base/kernel.yml
    - include_tasks: tasks/base/packages.yml
    - include_tasks: tasks/base/filesystem.yml
    - include_tasks: tasks/base/core.yml
    - include_tasks: tasks/base/users.yml
    - include_tasks: tasks/base/ssh.yml
    - include_tasks: tasks/base/timers-pre.yml
    - include_tasks: tasks/base/timers.yml
      with_items:
        - clean-cache
        - cache-updates
        - pacman-fy
        - vacuum-journals

    # Boot

    - include_tasks: tasks/boot/uefi.yml
      when: boot_mode == "uefi"
    - include_tasks: tasks/boot/legacy.yml
      when: boot_mode == "legacy"

    # Remote only

    - include_tasks: tasks/remote_server/{{ item }}.yml
      with_items:
        - rev
        - nginx
        - munin
        - atop
      when: remote_server

    # Local only

    - include_tasks: tasks/local_server/{{ item }}.yml
      with_items:
        - rev
        - scratch
      when: not remote_server

    # Compile server only

    - include_tasks: tasks/compile_server/{{ item }}.yml
      with_items:
        - packages
        - systemd
        - linux
      when: compile_server

    # Desktop only

    - include_tasks: tasks/desktop/{{ item }}.yml
      with_items:
        - packages
        - fonts
      when: desktop

    - include_tasks: tasks/desktop/{{ item }}.yml
      with_items:
        - cdown-packages
      when: desktop and cdown

    # Game server only

    - include_tasks: tasks/game_server/{{ item }}.yml
      with_items:
        - l4d2
      when: game_server

    # Currently unused: seedbox/

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart l4d2
      service: name=l4d2 state=restarted
