---
- hosts: localhost
  connection: local

  vars:
    users:
      - cdown

  vars_files:
    - vars/common.yml
    - /.ansiblevars

  tasks:
    - include: tasks/remove.yml
    - include: tasks/users.yml
    - include: tasks/sudo.yml
    - include: tasks/ssh.yml
    - include: tasks/apt.yml
    - include: tasks/ntp.yml
    - include: tasks/tools.yml
    - include: tasks/atop.yml
    - include: tasks/perf.yml
    - include: tasks/ansible-update.yml
    - include: tasks/rpi.yml
      when: rpi
    - include: tasks/nginx.yml
      when: nginx
    - include: tasks/l4d2.yml
      when: l4d2
    - include: tasks/apt_post.yml

  handlers:
    - name: restart ntp
      service: name=ntp state=restarted
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart atop
      service: name=atop state=restarted
    - name: restart l4d2
      service: name=l4d2 state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
