---
- hosts: localhost
  connection: local

  vars:
    kernel: linux-lts
    kernel_params: 'cgroup_no_v1=all audit=0'
    hdd_scheduler: mq-deadline
    ssd_scheduler: mq-deadline
    users:
      - cdown

  tasks:
    - include_tasks: tasks/locale.yml
    - include_tasks: tasks/sysctl.yml
    - include_tasks: tasks/sudo.yml
    - include_tasks: tasks/aur.yml
    - include_tasks: tasks/arch.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/rtorrent.yml
    - include_tasks: tasks/nginx.yml
    - include_tasks: tasks/rev.yml
    - include_tasks: tasks/munin.yml
    - include_tasks: tasks/atop.yml
    - include_tasks: tasks/timers-pre.yml
    - include_tasks: tasks/timers.yml
      with_items:
        - clean-cache
        - cache-updates
        - pacman-fy
        - munin-cron
        - restart-atop-midnight

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart rtorrent
      service: name=rtorrent state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
