---
- hosts: localhost
  connection: local

  vars:
    users:
      - cdown

  tasks:
    - include: tasks/users.yml
    - include: tasks/sudo.yml
    - include: tasks/ssh.yml
    - include: tasks/apt.yml
    - include: tasks/ntp.yml
    - include: tasks/tools.yml
    - include: tasks/atop.yml
    - include: tasks/perf.yml

  handlers:
    - name: restart ntp
      service: name=ntd state=restarted
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart atop
      service: name=atop state=restarted
