---
- hosts: localhost
  connection: local

  vars:
    kernel: linux
    default_kernel_params: 'cgroup_no_v1=all audit=0 scsi_mod.use_blk_mq=1 page_poison=1 slab_nomerge=1 vsyscall=none mce=0'
    extra_kernel_params: ''
    users:
      - cdown

  tasks:
    - include_tasks: tasks/locale.yml
    - include_tasks: tasks/sysctl.yml
    - include_tasks: tasks/arch.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/sudo.yml
    - include_tasks: tasks/rtorrent.yml
    - include_tasks: tasks/nginx.yml
    - include_tasks: tasks/rev.yml

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart rtorrent
      service: name=rtorrent state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
