---
- hosts: localhost
  connection: local

  vars:
    kernel: linux
    default_kernel_params: 'cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1'
    extra_kernel_params: ''
    users:
      - cdown

  tasks:
    - include_tasks: tasks/arch.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/sudo.yml
    - include_tasks: tasks/rtorrent.yml

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
