---
- hosts: localhost
  connection: local

  tasks:
    - include: tasks/apt.yml
    - include: tasks/ntp.yml
    - include: tasks/ssh.yml
    - include: tasks/tools.yml
    - include: tasks/atop.yml
    - include: tasks/perf.yml

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
    - name: restart sshd
      service: name=sshd state=restarted
    - name: restart atop
      service: name=atop state=restarted
