---

# TODO:
#
# - Run as separate user and don't hardcode
# - Populate GeoLite2.mmdb via a... supported method
# - Use cargo binstall
# - Hotswap

- name: Make geoip-http dir
  file: path=/opt/geoip-http state=directory mode=0755

- name: Download geoip-http
  get_url:
    url: https://github.com/cdown/geoip-http/releases/download/0.2.0/geoip-http
    dest: /opt/geoip-http/geoip-http
    checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c

- name: Download jank GeoLite2 (lol)
  get_url:
    url: https://cdn.jsdelivr.net/npm/geolite2-city@1.0.0/GeoLite2-City.mmdb.gz
    dest: /opt/geoip-http/GeoLite2-City.mmdb.gz
    checksum: sha256:616b1d9af14edaf06a12e47c7a0b9a3369a728e95f4ce35c917dd4760a9c0ba8
  register: dl

- name: Extract GeoLite2
  unarchive: src=/opt/geoip-http/GeoLite2-City.mmdb.gz dest=/opt/geoip-http/GeoLite2-City.mmdb
  when: dl.changed

- copy: src=files/geoip-http.service dest=/etc/systemd/system/geoip-http.service
- systemd: name=geoip-http.service enabled=yes daemon_reload=yes
