---

# TODO:
#
# - Use cargo binstall
# - Hotswap

- name: Make geoip-http dir
  file: path=/opt/geoip-http state=directory mode=0755

- name: Fetch SHA256 checksum
  uri:
    url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={{ maxmind_token }}&suffix=tar.gz.sha256"
    return_content: yes
  register: checksum_response

- name: Download geoip-http
  get_url:
    url: https://github.com/cdown/geoip-http/releases/download/0.2.0/geoip-http
    dest: /opt/geoip-http/geoip-http
    checksum: sha256:f9ac406ee1fe5d962448b48ea1f5b698903aa7652f93aea467059111d88b2bc9
    mode: '0755'

- name: Download GeoLite2 DBB
  get_url:
    url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={{ maxmind_token }}&suffix=tar.gz"
    dest: /opt/geoip-http/GeoLite2-City.mmdb.tar.gz
    checksum: "sha256:{{ checksum_response.content | split(' ') | first }}"
  register: dl

- name: Extract GeoLite2
  unarchive: src=/opt/geoip-http/GeoLite2-City.mmdb.tar.gz dest=/opt/geoip-http
  when: dl.changed

- copy: src=files/geoip-http.service dest=/etc/systemd/system/geoip-http.service
- systemd: name=geoip-http.service enabled=yes daemon_reload=yes

- name: Reload GeoIP DB
  uri:
    url: "http://localhost:3000/reload/geoip"
  when: dl.changed
