---
# TODO: Add IPv6 support: https://stanislas.blog/2019/01/how-to-setup-vpn-server-wireguard-nat-ipv6/

# Part of the old config which is gone now
- file: path=/etc/systemd/system/wg-quick@.service.d state=absent
- systemd: name=wg-quick@wg0.service state=stopped enabled=no daemon_reload=yes

- pacman: name=wireguard-tools
- pacman: name=qrencode  # to show phone configs

### Users

# To regenerate, remove /srv/wireguard/keys

- stat: path=/srv/wireguard/keys
  register: wireguard_keys

- file: path=/srv/wireguard/keys state=directory owner=root mode=700

- shell: "umask 077 && wg genkey | tee /srv/wireguard/keys/1_{{ ansible_hostname }}_private_key | wg pubkey > /srv/wireguard/keys/1_{{ ansible_hostname }}_public_key"
  when: not wireguard_keys.stat.exists

- stat: path=/srv/wireguard/keys/{{ item.final_octet }}_{{ item.name }}_private_key
  with_items: "{{ wireguard_users }}"
  register: wireguard_clients

# syncconf is not done automatically to avoid problems. Afterwards:
#
# wg syncconf wg0 <(wg-quick strip wg0)
- shell: "umask 077 && wg genkey | tee /srv/wireguard/keys/{{ item.item.final_octet }}_{{ item.item.name }}_private_key | wg pubkey > /srv/wireguard/keys/{{ item.item.final_octet }}_{{ item.item.name }}_public_key"
  with_items: "{{ wireguard_clients.results }}"
  when: not item.stat.exists

### Server config

- name: Copy generate WireGuard server config script
  copy: src=files/wireguard/generate-wireguard-server-config dest=/usr/local/bin/generate-wireguard-server-config mode=755

- name: Generate WireGuard server config
  command: generate-wireguard-server-config
  register: gwsc
  changed_when: false

- name: Copy WireGuard server config
  copy: content="{{ gwsc.stdout }}\n" dest=/etc/wireguard/wg0.conf owner=root mode=600

- name: Copy vpn.service
  copy: src=files/vpn.service dest=/etc/systemd/system/vpn.service

- name: Start WireGuard server
  systemd: name=vpn.service state=started enabled=yes daemon_reload=yes

### Client config generator

- name: Copy generate WireGuard server config script
  copy: src=files/wireguard/generate-wireguard-client-config dest=/usr/local/bin/generate-wireguard-client-config mode=755

### DNS

- pacman: name=unbound

- include_tasks: tasks/base/timers.yml
  with_items:
    - unbound-root-hints-update

# Run once if the root hints are missing
- stat: path=/etc/unbound/root.hints
  register: root_hints

- systemd: name=unbound-root-hints-update.service state=started
  when: not root_hints.stat.exists

- copy: src=files/unbound.conf dest=/etc/unbound/unbound.conf
  notify: restart unbound

- file: path=/etc/systemd/system/unbound.service.d state=directory
- copy: src=files/force-unbound-after-wg.conf dest=/etc/systemd/system/unbound.service.d/override.conf

- systemd: name=unbound state=started enabled=yes daemon_reload=yes
