---
- name: Script to update from ansible-server
  copy: src=files/bin/ansible-update dest=/usr/local/bin/ansible-update mode=755

- name: Ansible update service
  copy: src=files/ansible-update.service dest=/etc/systemd/system/ansible-update.service

- name: Ansible update timer
  copy: src=files/ansible-update.timer dest=/etc/systemd/system/ansible-update.timer

- name: Start/enable ansible-update timer
  systemd: name=ansible-update.timer state=started enabled=yes daemon_reload=yes
