---
- name: Copy Pacman configuration
  copy: src=files/pacman.conf dest=/etc/pacman.conf

- name: Copy fstab
  copy: src=files/fstab dest=/etc/fstab

# Workaround to avoid https://github.com/ansible/ansible/issues/37334
- command: pacman -Qi base
  changed_when: False
  register: base_package_present
- command: pacman -S --noconfirm base
  when: base_package_present.rc != 0

- name: Install minimal base
  pacman:
    name:
      # These used to be part of the base group, but aren't part of the new
      # metapackage. After new `base` becomes stable, these should be moved to
      # relevant sections and justified there.
      - dhcpcd
      - less
      - linux-firmware
      - systemd-sysvcompat  # TODO: remove and just use init=...?

- name: Remove unused OVH tools
  pacman:
    state: absent
    name:
      - ethtool
      - hddtemp
      - irqbalance
      - jfsutils
      - dmidecode
      - grub
      - man-pages-de
      - man-pages-it
      - net
      - screen
      - tcpdump
      - smartmontools
      - vlan
      - wget
      - gnu-efi-libs
      - bc
      - numactl
      - haveged
      - parted
      - bind
      - ntp

- name: Nuke motd
  copy: content="" dest=/etc/motd

- name: Install kernel + LTS as backup
  pacman:
    name:
      - '{{ kernel }}'
      - linux-lts

- name: Copy generate syslinux script
  copy: src=files/bin/generate-syslinux-config dest=/usr/local/bin/generate-syslinux-config mode=755

- name: Install packages needed for boot
  pacman:
    name:
      - syslinux
      - intel-ucode
      - kexec-tools

- name: Generate syslinux config
  command: "generate-syslinux-config {{ kernel }} '{{ kernel_params }}'"
  register: gsc
  changed_when: false

- name: Copy syslinux config
  copy: 'content="{{ gsc.stdout }}\n" dest=/boot/syslinux/syslinux.cfg'

- name: Install syslinux to /boot
  command: syslinux-install_update -i -a -m
  changed_when: false

- name: Install tools
  pacman:
    name:
      - zsh
      - htop
      - mosh
      - rsync
      - tmux
      - vim
      - btrfs-progs
      - git
      - python
      - mktorrent
      - p7zip
      - lsof
      - bind-tools
      - pacman-contrib

- name: Install music tools
  pacman:
    name:
      - flac
      - lame

- name: Enable systemd-timesyncd
  service: name=systemd-timesyncd state=started enabled=yes

- name: Script to update from ansible-server
  copy: src=files/bin/ansible-update dest=/usr/local/bin/ansible-update mode=755

- name: Set I/O schedulers
  template: src=files/io-schedulers.rules dest=/etc/udev/rules.d/99-io-schedulers.rules
