---
- name: Remove unused
  pacman: name={{ item }} state=absent recurse=yes
  with_items:
    - lvm2

- name: Nuke motd
  copy: content="" dest=/etc/motd

- name: Install kernel
  pacman: name={{ kernel }}

- name: Copy generate syslinux script
  copy: src=files/bin/generate-syslinux-config dest=/usr/local/bin/generate-syslinux-config mode=755

- name: Install packages needed for boot
  pacman: name={{ item }}
  with_items:
    - syslinux
    - intel-ucode

- name: Generate syslinux config
  command: "generate-syslinux-config {{ kernel }} '{{ default_kernel_params }} {{ extra_kernel_params }}'"
  register: gsc
  changed_when: false

- name: Copy syslinux config
  copy: 'content="{{ gsc.stdout }}\n" dest=/boot/syslinux/syslinux.cfg'

- name: Install syslinux to /boot
  command: syslinux-install_update -i -a -m
  changed_when: false

- name: Script to update from ansible-server
  copy: src=files/bin/ansible-update dest=/usr/local/bin/ansible-update mode=755

- name: Ansible update service
  copy: src=files/ansible-update.service dest=/etc/systemd/system/ansible-update.service

- name: Ansible update timer
  copy: src=files/ansible-update.timer dest=/etc/systemd/system/ansible-update.timer

- name: Start/enable ansible-update timer
  systemd: name=ansible-update.timer state=started enabled=yes daemon_reload=yes

- name: Install tools
  pacman: name={{ item }}
  with_items:
    - zsh
    - htop
    - mosh
    - rsync
    - tmux

- name: Install atop
  pacman: name=atop

- name: Disable unused atop service, using atop-oneday instead
  systemd: name=atop state=stopped enabled=no daemon_reload=yes

- name: Install atop oneday script
  copy: src=files/bin/atop-oneday dest=/usr/local/bin/atop-oneday mode=755

- name: Install atop oneday service
  copy: src=files/atop-oneday.service dest=/etc/systemd/system/atop-oneday.service

- name: Start/enable atop-oneday
  systemd: name=atop-oneday state=started enabled=yes daemon_reload=yes
