---
- name: Install atop
  pacman: name=atop

- name: Disable unused atop service, using atop-oneday instead
  systemd: name=atop state=stopped enabled=no daemon_reload=yes

- name: Install atop oneday script
  copy: src=files/bin/atop-oneday dest=/usr/local/bin/atop-oneday mode=755

- name: Install atop oneday service
  copy: src=files/atop-oneday.service dest=/etc/systemd/system/atop-oneday.service

- name: Start/enable atop-oneday
  systemd: name=atop-oneday state=started enabled=yes daemon_reload=yes

- name: Service to purge atop logs
  copy: src=files/purge-atop-logs.service dest=/etc/systemd/system/purge-atop-logs.service

- name: Timer to purge atop logs
  copy: src=files/purge-atop-logs.timer dest=/etc/systemd/system/purge-atop-logs.timer

- name: Start/enable purge-atop-logs timer
  systemd: name=purge-atop-logs.timer state=started enabled=yes daemon_reload=yes
