---
- name: Add steam user
  user: name=steam shell=/bin/zsh

- name: Install steamcmd deps
  apt: name=lib32gcc1

- stat: path=~steam/steamcmd.sh
  register: steamcmd_stat

- stat: path=~steam/l4d2
  register: l4d2_stat

- name: Download steamcmd
  get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    dest: /tmp/steamcmd.tar.gz
  when: not steamcmd_stat.stat.exists
  register: downloaded_steamcmd

- name: Extract steamcmd
  unarchive: src=/tmp/steamcmd.tar.gz dest=~steam/
  sudo: yes
  sudo_user: steam
  when: downloaded_steamcmd.changed

- name: Install L4D2
  command: ~steam/steamcmd.sh +login anonymous +force_install_dir ~steam/l4d2 +app_update 222860 validate +quit
  when: not l4d2_stat.stat.exists

- name: Configure L4D2 server.cfg
  copy: src=files/l4d2_config dest=~steam/l4d2/left4dead2/cfg/server.cfg mode=644 owner=steam
  notify: restart l4d2

- name: Install run_l4d2
  copy: src=files/run_l4d2 dest=/usr/local/bin/run_l4d2 mode=755
  notify: restart l4d2

- name: Install L4D2 systemd service
  copy: src=files/l4d2.service dest=/etc/systemd/system/l4d2.service
  notify: restart l4d2

- name: Make .steam dir
  file: path=~steam/.steam state=directory mode=0755 owner=steam group=steam

- name: Make sdk32 dir
  file: path=~steam/.steam/sdk32 state=directory mode=0755 owner=steam group=steam

- name: Link steamclient.so
  file: src=~steam/linux32/steamclient.so dest=~steam/.steam/sdk32/steamclient.so state=link
  notify: restart l4d2

- name: Start and enable L4D2
  service: name=l4d2 state=started enabled=yes
