---
- name: Install NTP daemon
  apt: name=ntp

- name: Install NTP config
  copy: src=files/ntp.conf dest=/etc/ntp.conf mode=644
  notify: restart ntpd

- name: Enable NTP daemon
  service: name=ntp state=started enabled=yes
