---
- name: Remove unwanted packages
  apt: name={{ item }} state=absent
  with_items:
    - rpcbind
    - avahi-daemon
    - exim4
    - exim4-base
    - exim4-config
    - exim4-daemon-light
    - acpid
