---
- name: Install create_ap dependencies
  apt: name={{ item }}
  with_items:
    - iw
    - wireless-tools
    - hostapd
    - haveged

- name: Make create_ap dir
  file: path={{ cap_dir }} state=directory

- stat: path={{ cap_tgz }}
  register: cap_stat

- name: Download create_ap {{ create_ap_version }}
  get_url:
    url: https://github.com/oblique/create_ap/archive/v0.4.6.tar.gz
    dest: "{{ cap_tgz }}"
  when: not cap_stat.stat.exists
  register: downloaded_cap

- name: Extract create_ap {{ create_ap_version }}
  unarchive: src={{ cap_tgz }} dest={{ cap_dir }}
  when: downloaded_cap.changed
