---
- name: Remove packages that would try to manage the network themselves
  apt: name={{ item }} state=absent
  with_items:
    - ifupdown

- name: Disable default dhcpcd service
  systemd: name=dhcpcd state=stopped enabled=no daemon_reload=yes

- name: Install dhcpcd@ service
  copy: src=files/dhcpcd@.service dest=/etc/systemd/system/dhcpcd@.service

- name: Enable core interface on boot
  systemd: name=dhcpcd@{{ cap_device }} state=started enabled=yes daemon_reload=yes

- name: Install create_ap dependencies
  apt: name={{ item }}
  with_items:
    - iw
    - wireless-tools
    - hostapd
    - haveged

- name: Make create_ap dir
  file: path={{ cap_dir }} state=directory

- stat: path={{ cap_tgz }}
  register: cap_stat

- name: Download create_ap {{ create_ap_version }}
  get_url:
    url: https://github.com/oblique/create_ap/archive/v0.4.6.tar.gz
    dest: "{{ cap_tgz }}"
  when: not cap_stat.stat.exists
  register: downloaded_cap

- name: Extract create_ap {{ create_ap_version }}
  unarchive: src={{ cap_tgz }} dest={{ cap_dir }}
  when: downloaded_cap.changed

- name: Install create_ap systemd unit
  template: src=files/pifi.service dest=/etc/systemd/system/pifi.service
  notify: restart pifi

- name: Enable/start pifi unit
  systemd: name=pifi state=started enabled=yes daemon_reload=yes
