---
- sysctl: name=vm.panic_on_oom value=1
- sysctl: name=kernel.panic_on_oops value=1
- sysctl: name=kernel.panic value=-1
- sysctl: name=kernel.sysrq value=1
- sysctl: name=kernel.pid_max value=4194304

# Print messages at KERN_WARNING and above. Make unspecified printk() calls
# use KERN_WARNING, since otherwise no stacktraces get printed to the console.
# This avoids console spew from KERN_INFO/KERN_NOTICE, while still ensuring
# that we can debug problems.
- sysctl: name=kernel.printk value="5 4 1 5"

# ...and now that we've done that, we can make debugging OOMs a little easier.
- sysctl: name=vm.oom_dump_tasks value=1

# Default sysctls for network buffers strike a poor balance between being too
# small to allow large transfers, but large enough to still cause memory
# pressure for sensitive applications.
- sysctl: name=net.core.{{ item }}_max value=67108864
  with_items:
    - rmem
    - wmem
- sysctl: name=net.ipv4.tcp_{{ item }} value="4096 125000 67108864"
  with_items:
    - rmem
    - wmem

# Alleviate contention when rtorrent has a lot of peers at once
- sysctl: name=net.ipv4.ip_local_port_range value="10000 64999"
- sysctl: name=net.ipv4.tcp_max_syn_backlog value=8192
- sysctl: name=net.ipv4.tcp_fin_timeout value=5
- sysctl: name=net.core.somaxconn value=4096

# Resetting to slow start after a single RTO (~200ms) is a bit absurd, since it
# will likely end up with a bunch of connections always in slow start
- sysctl: name=net.ipv4.tcp_slow_start_after_idle value=0
- sysctl: name=net.ipv4.tcp_fastopen value=3

# Enable BPF JIT
- sysctl: name=net.core.bpf_jit_enable value=1
- sysctl: name=net.core.bpf_jit_kallsyms value=1

# netsec
- sysctl: name=net.ipv4.conf.default.accept_source_route value=0
- sysctl: name=net.ipv4.conf.default.rp_filter value=2
- sysctl: name=net.ipv4.conf.all.rp_filter value=2
- sysctl: name=net.ipv4.ip_forward value=0

# Our workload benefits a lot from VFS caching, so be # more willing to keep it
# in memory.
- sysctl: name=vm.vfs_cache_pressure value=50

# Thanks, rusty HDDs.
#
# Hey, if you're reading this, don't just blindly copy this value. Read
# https://chrisdown.name/2018/01/02/in-defence-of-swap.html.
- sysctl: name=vm.swappiness value=50

# If ICMP actually works (see docs for value 1), this won't kick in. No reason
# not to enable it, then.
- sysctl: name=net.ipv4.tcp_mtu_probing value=1

# Only not the default because BBR is so new, I suppose. No reason not to use
# the new hotness.
- sysctl: name=net.ipv4.tcp_congestion_control value=bbr
