---
- name: Be reluctant to swap
  sysctl: name=vm.swappiness value=0

- name: Panic on OOM
  sysctl: name=vm.panic_on_oom value=1

- name: Panic on oops
  sysctl: name=kernel.panic_on_oops value=1

- name: Reboot 2 seconds after panic
  sysctl: name=kernel.panic value=2

- name: Enable magic sysrq
  sysctl: name=kernel.sysrq value=0
