---
- name: Be reluctant to swap (thanks, rusty HDDs)
  sysctl: name=vm.swappiness value=10

- name: Panic on OOM
  sysctl: name=vm.panic_on_oom value=1

- name: Panic on oops
  sysctl: name=kernel.panic_on_oops value=1

- name: Reboot 2 seconds after panic
  sysctl: name=kernel.panic value=2

- name: Enable magic sysrq
  sysctl: name=kernel.sysrq value=0

- name: Increase socket buffers to 16M for rtorrent
  sysctl: name=net.core.{{ item }}_max value=16777216
  with_items:
    - rmem
    - wmem

- name: Increase TCP buffer size for rtorrent
  sysctl: name=net.ipv4.tcp_{{ item }} value="4096 12582912 16777216"
  with_items:
    - rmem
    - wmem

- sysctl: name=net.ipv4.ip_local_port_range value="10000 65000"
- sysctl: name=net.core.netdev_max_backlog value=50000
- sysctl: name=net.ipv4.tcp_max_syn_backlog value=30000
- sysctl: name=net.ipv4.tcp_max_tw_buckets value=2000000
- sysctl: name=net.ipv4.tcp_fin_timeout value=10
