---
- name: Make /var/log/journal dir
  file: path=/var/log/journal state=directory mode=2755 owner=root group=systemd-journal
  register: journal_dir
  notify: restart journald

- name: Set up tmpfiles
  command: systemd-tmpfiles --create --prefix /var/log/journal
  when: journal_dir.changed
  notify: restart journald

- name: Install /tmp -> tmpfs unit
  copy: src=files/tmp.mount dest=/etc/systemd/system/tmp.mount

- name: Enable /tmp -> tmpfs
  systemd: name=tmp.mount state=started enabled=yes daemon_reload=yes
