---
- name: Create local users
  user: name={{ item }} shell=/bin/zsh
  with_items: '{{ users }}'

- name: Set up SSH dir for cdown
  file: path=~cdown/.ssh state=directory mode=0700 owner=cdown group=cdown
  when: '"cdown" in users'

- name: Install SSH key for cdown
  copy: src=files/cdown_ssh_pubkey dest=~cdown/.ssh/authorized_keys mode=600 owner=cdown group=cdown
  when: '"cdown" in users'

- name: Check if cdown lingers
  stat: path=/var/lib/systemd/linger/cdown
  register: linger

- name: Enable linger for cdown
  command: loginctl enable-linger cdown
  when: 'not linger.stat.exists and "cdown" in users'
