---
- name: Install linux build dependencies
  pacman:
    name:
      - bc

# On server, no point in having GTK frontend. qemu-desktop comes from
# desktop/packages if on a desktop.
- pacman: name=qemu-base
  when: not desktop
