---
- name: Install linux build dependencies
  pacman:
    name:
      - bc

# On server, no point in having GTK frontend.
- pacman: name=qemu-desktop
  when: desktop
- pacman: name=qemu-base
  when: not desktop
