---
- name: Install linux build dependencies
  pacman:
    name:
      - bc

# On server, no point in having GTK frontend.
- pacman: name=qemu
  when: desktop
- pacman: name=qemu-headless
  when: not desktop
