---
- name: Add steam user
  user: name=steam shell=/bin/zsh

- name: Install steamcmd deps
  pacman: name=lib32-gcc-libs

- stat: path=~steam/steamcmd.sh
  register: steamcmd_stat

- stat: path=~steam/l4d2
  register: l4d2_stat

- name: Download steamcmd
  get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    dest: /tmp/steamcmd.tar.gz
  when: not steamcmd_stat.stat.exists
  register: downloaded_steamcmd

- name: Extract steamcmd
  unarchive: src=/tmp/steamcmd.tar.gz dest=~steam/
  become: yes
  become_user: steam
  when: downloaded_steamcmd.changed

- name: Install L4D2
  command: ~steam/steamcmd.sh +login anonymous +force_install_dir ~steam/l4d2 +app_update 222860 validate +quit
  when: not l4d2_stat.stat.exists

- name: Configure L4D2 server.cfg
  copy: src=files/l4d2_config dest=~steam/l4d2/left4dead2/cfg/server.cfg mode=644 owner=steam
  notify: restart l4d2

- name: Install run_l4d2
  copy: src=files/run_l4d2 dest=/usr/local/bin/run_l4d2 mode=755
  notify: restart l4d2

- name: Install L4D2 systemd service
  copy: src=files/l4d2.service dest=/etc/systemd/system/l4d2.service
  notify: restart l4d2

- name: Make .steam dir
  file: path=~steam/.steam state=directory mode=0755 owner=steam group=steam

- name: Make sdk32 dir
  file: path=~steam/.steam/sdk32 state=directory mode=0755 owner=steam group=steam

- name: Link steamclient.so
  file: src=~steam/linux32/steamclient.so dest=~steam/.steam/sdk32/steamclient.so state=link
  notify: restart l4d2

- stat: path=~steam/l4d2/left4dead2/addons/metamod/
  register: mm_stat

- name: Download MetaMod
  get_url:
    url: https://mms.alliedmods.net/mmsdrop/1.11/mmsource-1.11.0-git1144-linux.tar.gz
    dest: /tmp/mm.tar.gz
  when: not mm_stat.stat.exists
  register: downloaded_mm

# For the next task
- pacman: name=unzip

- name: Extract MetaMod
  unarchive: src=/tmp/mm.tar.gz dest=~steam/l4d2/left4dead2/
  become: yes
  become_user: steam
  when: downloaded_mm.changed
  notify: restart l4d2

- stat: path=~steam/l4d2/left4dead2/addons/sourcemod/
  register: sm_stat

- name: Download SourceMod
  get_url:
    url: https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6502-linux.tar.gz
    dest: /tmp/sm.tar.gz
  when: not sm_stat.stat.exists
  register: downloaded_sm

- name: Extract SourceMod
  unarchive: src=/tmp/sm.tar.gz dest=~steam/l4d2/left4dead2/
  become: yes
  become_user: steam
  when: downloaded_sm.changed
  notify: restart l4d2

- name: Set up SM admins
  copy: src=files/sm_admins dest=~steam/l4d2/left4dead2/addons/sourcemod/configs/admins_simple.ini owner=steam
  notify: restart l4d2

# https://forums.alliedmods.net/showthread.php?p=2409064
- name: l4d_survivor_bot_select.smx
  copy: src=files/l4d2/l4d_survivor_bot_select.smx dest=~steam/l4d2/left4dead2/addons/sourcemod/plugins/l4d_survivor_bot_select.smx owner=steam
  notify: restart l4d2

- name: l4d_survivor_bot_select.txt
  copy: src=files/l4d2/l4d_survivor_bot_select.txt dest=~steam/l4d2/left4dead2/addons/sourcemod/gamedata/l4d_survivor_bot_select.txt owner=steam
  notify: restart l4d2

# https://forums.alliedmods.net/showthread.php?p=893326
- name: l4d_survivorai_pouncedfix.smx
  copy: src=files/l4d2/l4d_survivorai_pouncedfix.smx dest=~steam/l4d2/left4dead2/addons/sourcemod/plugins/l4d_survivorai_pouncedfix.smx owner=steam
  notify: restart l4d2

- name: Start and enable L4D2
  systemd: name=l4d2 state=started enabled=yes daemon_reload=yes

- name: Copy timer to restart L4D2 nightly
  copy: src=files/l4d2-restart.timer dest=/etc/systemd/system/l4d2-restart.timer

- name: Copy service to restart L4D2 nightly
  copy: src=files/l4d2-restart.service dest=/etc/systemd/system/l4d2-restart.service

- name: Start and enable L4D2 restart service
  systemd: name=l4d2-restart.timer state=started enabled=yes daemon_reload=yes
