#!/bin/bash -e

wired_iface=$(get-wired-interface)
ntp_port=123

additional_ports=(
    # RDP
    3389

    # WireGuard default
    51820
)

rules=()

for port in "${additional_ports[@]}"; do
    rules+=(
        "POSTROUTING -o $wired_iface -j MASQUERADE"
        "PREROUTING -i $wired_iface -p udp -m multiport --dports $port -j REDIRECT --to-ports $ntp_port"
    )
done

post_up=''
post_down=''

for rule in "${rules[@]}"; do
    for cmd in iptables ip6tables; do
        post_up+=" $cmd -t nat -A $rule; "
        post_down+=" $cmd -t nat -D $rule; "
    done
done


cat << EOF
[Interface]
Address = 10.200.200.1/24, fd42:42:42::1/64
SaveConfig = false
PrivateKey = $(< /srv/wireguard/keys/1_"${HOSTNAME}"_private_key)
ListenPort = $ntp_port
PostUp   = $post_up
PostDown = $post_down

EOF

for file in /srv/wireguard/keys/*_public_key; do
    octet=${file##*/}
    octet=${octet%%_*}

    user=${file##*/}
    user=${user#*_}
    user=${user%%_*}
    [[ $user == "$HOSTNAME" ]] && continue

    cat << EOF
[Peer]
# $user
PublicKey = $(< "$file")
AllowedIPs = 10.200.200.$octet/32, fd42:42:42::$octet/128

EOF
done
