#!/bin/bash -e

wanted=${1?}

case $(uname -n) in
    choudoufu) endpoint=home.chrisdown.name:123 ;;
    youyuan) endpoint=youyuan.chrisdown.name:123 ;;
    *) exit 1 ;;
esac

for file in /srv/wireguard/keys/*_private_key; do
    octet=${file##*/}
    octet=${octet%%_*}

    user=${file##*/}
    user=${user#*_}
    user=${user%%_*}

    [[ $user == "$HOSTNAME" ]] && continue

    [[ $user == "$wanted" ]] || continue

    # The WireGuard android app doesn't like SaveConfig
    starter="cat << 'EOF' | sudo tee /etc/wireguard/$HOSTNAME.conf > /dev/null"
    ender=EOF
    phone_unknown_lines='SaveConfig = false'
    cmd=(cat)
    if [[ $user == *-phone ]]; then
        phone_unknown_lines=''
        starter=''
        ender=''
        cmd=(qrencode -t ansiutf8)
    fi

    cat << _EOF | "${cmd[@]}"
$starter
[Interface]
Address = 10.200.200.$octet/32, fd42:42:42::$octet/64
PrivateKey = $(cat "$file")
DNS = 10.200.200.1
$phone_unknown_lines

[Peer]
PublicKey = $(cat /srv/wireguard/keys/1_"${HOSTNAME}"_public_key)
Endpoint = $endpoint
AllowedIPs = 0.0.0.0/0, ::0/0
PersistentKeepalive = 21
$ender
_EOF

    break
done
