---
- name: Install nodenv
  aur: name={{ item }} skip_installed=yes
  with_items:
    - nodenv
    - nodenv-node-build
  become: yes
  become_user: makepkg

- name: Check if node is installed in nodenv
  shell: "eval \"$(nodenv init -)\" && nodenv version"
  register: nodenv_version
  become: yes
  become_user: "{{ user }}"
  changed_when: false
  failed_when: 'nodenv_version.rc != 0 and nodenv_version.stdout_lines'

- name: Install node {{ node_version }} using nodenv
  shell: "eval \"$(nodenv init -)\" && nodenv install {{ node_version }} && nodenv rehash && nodenv global {{ node_version }}"
  become: yes
  become_user: "{{ user }}"
  when: 'nodenv_version.rc != 0 or node_version not in nodenv_version.stdout'

- name: Get list of installed packages
  shell: "eval \"$(nodenv init -)\" && npm ls -g | awk '$NF ~ /@/ { print $NF }' | awk -F@ '{ print $1 }'"
  register: nodenv_packages
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install node utilities
  shell: 'eval "$(nodenv init -)" && npm install -g {{ item }} && nodenv rehash'
  with_items:
    - arch-wiki-man
    - twly
  become: yes
  become_user: "{{ user }}"
  when: '(item|basename) not in nodenv_packages.stdout_lines'
