---
- name: Install pyenv
  aur: name=pyenv skip_installed=yes
  become: yes
  become_user: makepkg

- name: Get active Python installed in pyenv
  shell: "cat ~/.pyenv/version"
  register: pyenv_version
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- copy: src=files/bin/pyenv-check-rebuild-needed dest=/usr/local/bin/pyenv-check-rebuild-needed mode=755
- copy: src=files/bin/pyenv-init-full dest=/usr/local/bin/pyenv-init-full mode=755

- name: Check if Python needs a rebuild for dynamic lib update
  command: pyenv-check-rebuild-needed
  become: yes
  become_user: "{{ user }}"
  register: python_needs_force_rebuild
  ignore_errors: yes
  changed_when: false

- name: Install Python 3 using pyenv
  shell: "eval \"$(pyenv-init-full)\" && pyenv install {{ '-f' if python_needs_force_rebuild.rc != 0 }} {{ python_3_version }}"
  become: yes
  become_user: "{{ user }}"
  when: 'python_needs_force_rebuild.rc != 0 or python_3_version not in pyenv_version.stdout_lines'

- name: Get currently installed pyenv versions
  shell: "eval \"$(pyenv-init-full)\" && pyenv versions --bare"
  register: installed_versions
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Purge all other Python versions
  shell: "eval \"$(pyenv-init-full)\" && pyenv uninstall -f {{ item }}"
  with_items: "{{ installed_versions.stdout_lines }}"
  when: "item != python_3_version"
  become: yes
  become_user: "{{ user }}"

- name: Get list of Python 3 utils installed
  shell: "eval \"$(pyenv-init-full)\" && pyenv shell {{ python_3_version }} && pip freeze --all | awk -F= '{ print $1 }'"
  register: py3_utils
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- pacman: name=ffmpeg  # for yt-dlp

- name: Install pipx
  shell: 'eval "$(pyenv-init-full)" && pyenv shell {{ python_3_version }} && python -m pip install -U pipx'
  become: yes
  become_user: "{{ user }}"
  when: '"pipx" not in py3_utils.stdout_lines'

- name: Reinstall pipx applications after pyenv Python rebuild
  shell: 'eval "$(pyenv-init-full)" && pyenv shell {{ python_3_version }} && pipx reinstall-all --python "$(pyenv which python)"'
  become: yes
  become_user: "{{ user }}"
  when: 'python_needs_force_rebuild.rc != 0 or python_3_version not in pyenv_version.stdout_lines'

- name: Get list of pipx packages installed
  shell: 'eval "$(pyenv-init-full)" && pyenv shell {{ python_3_version }} && pipx list --short --include-injected'
  register: pipx_packages
  become: yes
  become_user: "{{ user }}"
  failed_when: false
  changed_when: false

- name: Install Python 3 utilities with pip
  shell: 'eval "$(pyenv-init-full)" && pyenv shell {{ python_3_version }} && pip install -U {{ item }}'
  with_items:
    - pip
    - virtualenv
    - virtualenvwrapper
    - astroid
    - psutil
    - jupyter
    - ipython
    - line-profiler
    - memory-profiler
    - graphviz
    - tabulate
    - mutagen
    - chardet
  become: yes
  become_user: "{{ user }}"
  when: 'not item.startswith("git+https://") and (item|basename) not in py3_utils.stdout_lines'

- name: Install Python 3 CLI applications with pipx
  shell: 'eval "$(pyenv-init-full)" && pyenv shell {{ python_3_version }} && pipx install --python "$(pyenv which python)" {{ item }}'
  with_items:
    - pylint
    - twine
    - flake8
    - awscli
    - tox
    - pipdeptree
    - srt
    - yt-dlp
    - black
    - certbot
    - gprof2dot
    - beets
    - codemod
    - whensthebus
    - csvprint
    - stapler
    - gsutil
    - s3cmd
    - ffsubsync
    - gmute
    - icdiff
    - habitual
    - diffoscope
    - get-cover-art
  become: yes
  become_user: "{{ user }}"
  when: 'item not in pipx_packages.stdout_lines'

- name: Inject srt support packages into pipx environment
  shell: 'eval "$(pyenv-init-full)" && pyenv shell {{ python_3_version }} && pipx inject srt hanzidentifier'
  become: yes
  become_user: "{{ user }}"
  when: '"hanzidentifier" not in pipx_packages.stdout_lines'

- name: Uninstall Python 3 utilities
  shell: 'eval "$(pyenv-init-full)" && pyenv shell {{ python_3_version }} && pip uninstall -y {{ item }}'
  with_items:
    - tzupdate
  become: yes
  become_user: "{{ user }}"
  when: '(item|basename) in py3_utils.stdout_lines'
