---
- name: Install rbenv
  aur: name={{ item }} skip_installed=yes
  with_items:
    - ruby  # host ruby is required to build
    - rbenv
    - ruby-build
  become: yes
  become_user: makepkg

- name: Get list of Rubies installed in rbenv
  shell: "eval \"$(rbenv init -)\" && rbenv versions | sed 's/^..//' | awk '{ print $1 }'"
  register: rbenv_versions
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Rubies using rbenv
  shell: "eval \"$(rbenv init -)\" && rbenv install {{ item }} && rbenv global {{ item }}"
  with_items:
    - "{{ ruby_version }}"
  become: yes
  become_user: "{{ user }}"
  when: 'item not in rbenv_versions.stdout_lines'

- name: Get list of installed gems
  shell: "eval \"$(rbenv init -)\" && rbenv shell {{ ruby_version }} && gem list | awk '{ print $1 }'"
  register: rbenv_gems
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Ruby utilities
  shell: 'eval "$(rbenv init -)" && rbenv shell {{ ruby_version }} && gem install {{ item }} && rbenv rehash'
  with_items:
    - bundler
    - trello_cli
    - pomo
    - libnotify  # https://github.com/tj/pomo/issues/47
    - travis
    - pry
  become: yes
  become_user: "{{ user }}"
  when: '(item|basename) not in rbenv_gems.stdout_lines'
