---
- name: Install yay
  aur: name=yay-bin skip_installed=yes use=makepkg
  become: yes
  become_user: makepkg
  when: arch == "x86"

- name: Install yay
  aur: name=yay skip_installed=yes use=makepkg
  become: yes
  become_user: makepkg
  when: arch != "x86"
