---
- file: path=/var/lib/systemd/linger state=directory
- copy: content="" dest=/var/lib/systemd/linger/{{ user }}

- stat: path=~{{ user }}/git/dotfiles
  register: dotfiles_dir

- name: Clone dotfiles for {{ user }}
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/cdown/dotfiles.git dest=~{{ user }}/git/dotfiles accept_hostkey=yes update=no
  register: df_clone
  when: not dotfiles_dir.stat.exists

- name: Set up dotfiles for {{ user }}
  become: yes
  become_user: "{{ user }}"
  command: ./setup chdir="~{{ user }}/git/dotfiles"
  changed_when: false
  when: df_clone.changed
