---

# btrfs

- name: btrfs tools
  pacman:
    name:
      - btrfs-progs
  when: filesystem == "btrfs"

- include_tasks: tasks/timers.yml
  with_items:
    - btrfs-balance-root
  when: filesystem == "btrfs"

# ext4

- name: ext4 tools
  pacman:
    name:
      - e2fsprogs
  when: filesystem == "ext4"

# SSD

- name: TRIM tools
  pacman:
    name:
      - fstrim
  when: root_on_ssd

- include_tasks: tasks/timers.yml
  with_items:
    - fstrim-root
  when: root_on_ssd
