---
- name: Install minimal base
  pacman:
    name:
      - base
      - base-devel
      - linux-firmware
      - systemd-sysvcompat
      - util-linux
      - p7zip

      # Encryption
      - cryptsetup
      - device-mapper

      # Core tools
      - mosh
      - tmux
      - vim
      - ncdu
      - diffutils
      - less
      - zsh
      - parallel
      - zsh-syntax-highlighting

      # upgrade
      - ansible
      - git
      - rsync

      # unite
      - lsof

      # pacdiff
      - pacman-contrib

      # Debugging
      - gdb
      - strace
      - python-bcc  # bcc-tools optdepends
      - bcc-tools
      - perf
      - time
      - man-db
      - man-pages
      - htop
      - bind

      # Network
      - dhcpcd

      # Access
      - openssh
      - lftp


- name: Install minimal base (x86)
  pacman:
    name:
      - bpftrace
  when: arch == "x86"

- name: Install CPU microcode
  pacman: name={{ cpu_microcode }}
  when: cpu_microcode

- name: Install minimal base (AUR)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes
  with_items:
    - pacman-static
  become: yes
  become_user: makepkg
