---
- name: Install minimal base
  pacman:
    name:
      - base
      - base-devel
      - linux-firmware
      - systemd-sysvcompat
      - util-linux
      - p7zip
      - rebuild-detector

      # Encryption
      - cryptsetup
      - device-mapper

      # Core tools
      - mosh
      - tmux
      - ncdu
      - diffutils
      - less
      - zsh
      - parallel
      - zsh-syntax-highlighting
      - pv

      # upgrade
      - ansible
      - git
      - rsync

      # unite
      - lsof

      # pacdiff
      - pacman-contrib

      # Debugging
      - gdb
      - strace
      - python-bcc  # bcc-tools optdepends
      - bcc-tools
      - perf
      - time
      - man-db
      - man-pages
      - htop
      - bind

      # Network
      - dhcpcd

      # Access
      - openssh

      # EFI partition maintenance
      - dosfstools

- name: Install minimal base (x86)
  pacman:
    name:
      - bpftrace
  when: arch == "x86"

- name: Install CPU microcode
  pacman: name={{ cpu_microcode }}
  when: cpu_microcode

- name: Install minimal base (lowmem)
  pacman:
    name:
      # temporarily generally using vim-git until
      # https://bugs.archlinux.org/task/77475 is done
      - vim
  when: lowmem

- name: Install minimal base (AUR, non-lowmem)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes use=makepkg
  with_items:
    - pacman-static
    - vim-git
  become: yes
  become_user: makepkg
  when: not lowmem
