---
- name: Install minimal base
  pacman:
    name:
      - base
      - linux-firmware
      - systemd-sysvcompat
      - util-linux
      - 7zip
      - rebuild-detector

      # Encryption
      - cryptsetup
      - device-mapper

      # Core tools
      - mosh
      - tmux
      - vim
      - neovim
      - ncdu
      - diffutils
      - less
      - zsh
      - parallel
      - zsh-syntax-highlighting
      - pv
      - gptfdisk

      # upgrade
      - ansible
      - git
      - rsync

      # unite
      - lsof

      # pacdiff
      - pacman-contrib

      # Debugging
      - gdb
      - strace
      - python-bcc  # bcc-tools optdepends
      - bcc-tools
      - perf
      - time
      - man-db
      - man-pages
      - htop
      - bind

      # Network
      - dhcpcd

      # Access
      - openssh

      # EFI partition maintenance
      - dosfstools

- name: Install base-devel, weirdly there is still stuff in the group, so can't use normal pacman rule since it will check the group
  command: pacman -S --noconfirm --needed base-devel
  changed_when: false

- name: Install minimal base (x86)
  pacman:
    name:
      - bpftrace
  when: arch == "x86"

- name: Install CPU microcode
  pacman: name={{ cpu_microcode }}
  when:
    - cpu_microcode is not none

- name: Install minimal base (AUR, non-lowmem)
  aur: name={{ item }} skip_installed=yes skip_pgp_check=yes use=makepkg
  with_items:
    - pacman-static
  become: yes
  become_user: makepkg
  when: not lowmem
