---
- name: Install minimal base
  pacman:
    name:
      - base
      - base-devel
      - linux-firmware
      - systemd-sysvcompat
      - util-linux
      - p7zip

      # CPU microcode
      - intel-ucode

      # Encryption
      - cryptsetup
      - device-mapper

      # Core tools
      - mosh
      - tmux
      - vim
      - ncdu
      - diffutils
      - less
      - zsh
      - parallel
      - zsh-syntax-highlighting

      # upgrade
      - ansible
      - git
      - rsync

      # unite
      - lsof

      # pacdiff
      - pacman-contrib

      # Debugging
      - gdb
      - strace
      - bpftrace
      - bcc-tools
      - perf
      - time
      - man-db
      - man-pages
      - htop
      - bind

      # Network
      - dhcpcd

      # Access
      - openssh
