---
- name: Copy Pacman configuration
  template: src=files/pacman.conf dest=/etc/pacman.conf
  register: pacman_conf

- name: Copy makepkg configuration
  template: src=files/makepkg.conf dest=/etc/makepkg.conf

- name: Manual pacman repo update to sync new dbs
  command: pacman -Syy
  when: pacman_conf.changed

- name: Manual pacman file list update for new dbs
  command: pacman -Fy
  when: pacman_conf.changed

- name: Make sure we have latest pacman keys
  command: pacman -Sy --noconfirm --needed archlinux-keyring
  changed_when: false
  when: arch == "x86"

- name: Make sure we have latest pacman keys (ARM)
  command: pacman -Sy --noconfirm --needed archlinuxarm-keyring
  changed_when: false
  when: arch == "arm"

- name: Make sure we have latest pacman key trust
  command: pacman-key --populate archlinux
  changed_when: false
  when: arch == "x86"

- name: Make sure we have latest pacman key trust (ARM)
  command: pacman-key --populate archlinuxarm
  changed_when: false
  when: arch == "arm"

- pacman: name=reflector
- systemd: name=reflector.timer state=started enabled=yes daemon_reload=yes
