---
- name: Install SSH daemon
  pacman: name=openssh

- name: Install SSH config
  copy: src=files/sshd_config dest=/etc/ssh/sshd_config mode=644
  notify: restart sshd

# Run all pending handlers. Otherwise, we might restart ssh at the end despite
# stopping/disabling it here.
- meta: flush_handlers

# Make sure that we don't have ufw running for servers, or else if there's a
# failure half way, SSH may not be available.
- systemd: name=ufw state=stopped enabled=no masked=yes daemon_reload=yes
  when:
    - "'ufw' in ansible_facts.services"
    - server

- name: Enable SSH daemon
  systemd: name=sshd state=started enabled=yes daemon_reload=yes
  when: server or force_ssh

- name: Disable SSH daemon
  systemd: name=sshd state=stopped enabled=no daemon_reload=yes
  when: not server and not force_ssh

- name: Create ssh group
  group: name=ssh state=present

- name: Add local user to ssh group
  user: name={{ item }} groups=ssh append=yes
  with_items: '{{ users }}'
