---
- file: path=/etc/sysctl.conf state=absent

- template: src=files/sysctl.conf dest=/etc/sysctl.d/99-generic.conf
  register: sysctls

- systemd: name=systemd-modules-load state=started
  when: systemd_init and sysctls.changed

- name: Check current value of /sys/kernel/mm/lru_gen/enabled
  command: cat /sys/kernel/mm/lru_gen/enabled
  register: lru_gen_enabled

- name: Disable MGLRU
  copy:
    content: "n"
    dest: /sys/kernel/mm/lru_gen/enabled
  when: lru_gen_enabled.stdout != "0x0000"
