---
- file: path=/etc/sysctl.conf state=absent

- template: src=files/sysctl.conf dest=/etc/sysctl.d/99-generic.conf
  register: sysctls

- systemd: name=systemd-modules-load state=started
  when: systemd_init and sysctls.changed

- copy: src=files/kernel-settings.conf dest=/etc/tmpfiles.d/kernel-settings.conf
  register: copy_ks

- command: systemd-tmpfiles --create /etc/tmpfiles.d/kernel-settings.conf
  when: copy_ks.changed
