---
- copy: src=files/bin/internet-isnt-crappy dest=/usr/local/bin/internet-isnt-crappy mode=755

- name: Install cache-updates
  copy: src=files/bin/cache-updates dest=/usr/local/bin/cache-updates mode=755
