---
- name: Remove OVH users
  user: name=ntp state=absent

- name: Create local users
  user: name={{ item }} shell=/bin/zsh
  with_items: '{{ users }}'

- name: Set up SSH dir for users
  file: path=~{{ item }}/.ssh state=directory mode=0700 owner={{ item }} group={{ item }}
  with_items: '{{ users }}'

- name: Install SSH key for users
  copy: src=files/cdown_ssh_pubkey dest=~{{ item }}/.ssh/authorized_keys mode=600 owner={{ item }} group={{ item }}
  with_items: '{{ users }}'
