---
- name: Remove OVH users
  user: name=ntp state=absent

- name: Create local users
  user: name={{ item }} shell=/bin/zsh
  with_items: '{{ users }}'

- name: Set up SSH dir for cdown
  file: path=~cdown/.ssh state=directory mode=0700 owner=cdown group=cdown
  when: '"cdown" in users'

- name: Install SSH key for cdown
  copy: src=files/cdown_ssh_pubkey dest=~cdown/.ssh/authorized_keys mode=600 owner=cdown group=cdown
  when: '"cdown" in users'

- file: path=/var/lib/systemd/linger state=directory
- copy: content="" dest=/var/lib/systemd/linger/cdown
