---
- pacman:
    name:
      - munin
      - munin-node

- file: path={{ item }} state=directory owner=munin group=munin mode=0755
  with_items:
    - /srv/http/munin
    - /var/lib/munin
    - /var/log/munin

- copy: src=files/munin.conf dest=/etc/munin/munin.conf

- file: src=/usr/lib/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items:
    - cpu
    - df
    - df_inode
    - diskstats
    - forks
    - fw_packets
    - interrupts
    - irqstats
    - load
    - memory
    - munin_stats
    - open_files
    - open_inodes
    - proc_pri
    - processes
    - swap
    - threads
    - uptime
    - vmstat

- file: src=/usr/lib/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }}eno0 state=link
  with_items:
    - if_
    - if_err_

- systemd: name=munin-node state=started enabled=yes daemon_reload=yes

- name: Make nginx munin site
  copy: src=files/nginx_munin.conf dest=/etc/nginx/conf.d/munin.conf mode=644
  notify: restart nginx
