---
- user:
    name: rev
    createhome: true
    system: true
    home: /srv/rev
    shell: /bin/false
    skeleton: /dev/null
    groups:
      - ssh

- file: path=~rev/.ssh state=directory owner=rev group=rev

- copy:
    content: 'no-pty,no-agent-forwarding,no-X11-forwarding,command="/bin/echo do-not-send-commands" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/NOu5oRWhSUrSQJzNgbmRvCQZCYOKEB2xV+b2uEw+ifj2vFsWqE50Z8Y9cjSJOEcGS1iHvMEL5IcbNQ2j4bY1DRuldiaFIBYGuvDD2HuThavvgqSPx5j4xminGWi8fgJmQw1Y3hYGOh0ILnD71x12auqGc7remK4sKlt/xs24LpiM0P3GE8yh4DvE7zeJbIq8ABx0VKSZFtO5yKftf5KXPD75n1MJjsC++nU9Xg9trXbvtt+K+oAAcHFM4EtmBvqNFcxuBVRCKngOpO83CQuvwOL0LCKr28sUW28+YN81ODnoTlfqiaX8J1pZlBqfmhlFXzg7Sa1bY8HsjBYMthKl'
    dest: '~rev/.ssh/authorized_keys'
    mode: 0644
    owner: root
    group: root
