---
- pacman:
    name:
      - munin
      - munin-node

- file: path={{ item }} state=directory owner=munin group=munin mode=0755
  with_items:
    - /srv/http/munin
    - /var/lib/munin
    - /var/log/munin

- copy: src=files/munin.conf dest=/etc/munin/munin.conf

- file: src=/usr/lib/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items:
    - cpu
    - df
    - df_inode
    - diskstats
    - fw_packets
    - load
    - memory
    - swap
    - uptime
  notify: restart munin-node

- copy: src=files/munin-plugins/ping.conf dest=/etc/munin/plugin-conf.d/ping.conf

- copy: src=files/munin-plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} mode=755
  with_items:
    - psi
    - ping
  notify: restart munin-node

- file: src=/etc/munin/plugins/ping dest=/etc/munin/plugins/ping_packetloss state=link
  notify: restart munin-node

- systemd: name=munin-node state=started enabled=yes daemon_reload=yes

- name: Make nginx munin site
  template: src=files/nginx_munin.conf dest=/etc/nginx/conf.d/munin.conf mode=644
  notify: restart nginx

- include_tasks: tasks/base/timers.yml
  with_items:
    - munin-cron
