---
- name: Make nginx dir
  file: path=/etc/nginx state=directory mode=0755

- name: Make nginx conf.d dir
  file: path=/etc/nginx/conf.d state=directory mode=0755

- name: Configure nginx.conf
  copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf mode=644
  notify: restart nginx

- name: Configure mime.types
  copy: src=files/mime.types dest=/etc/nginx/mime.types mode=644
  notify: restart nginx

# If this is a remote server, the default site is the share. Otherwise, it's
# munin by default since there's no other site available.
- name: Make nginx default site if remote
  copy: src=files/nginx_default_site.conf dest=/etc/nginx/conf.d/default.conf mode=644
  when: remote_server
  notify: restart nginx

- name: Remove nginx default site if not remote
  file: path=/etc/nginx/conf.d/default.conf state=absent
  when: not remote_server
  notify: restart nginx

- name: Install nginx
  pacman: name=nginx

- name: Make default site dir
  file: path=/srv/http/default state=directory mode=0755 owner=cdown

- systemd: name=nginx state=started enabled=yes daemon_reload=yes
