#!/bin/bash -e

# WAN
#ip=$(curl 'https://api.ipify.org')

# LAN
ip=$(ip addr show dev "$(get-wired-interface)" | awk '$1 == "inet" { print $2 }' | sed 's/\/.*//')

if ! [[ $ip ]]; then
    echo "Failed to get IP!" >&2
    exit 13
fi

# can't use stdbuf because that uses 64-bit, but this is 32-bit. you'll get
# wrong timestamps without script to unbuffer, and messages may be delayed
exec /usr/bin/script -c "exec /home/steam/l4d2/srcds_run +ip $ip -port 27015 +map c1m4_atrium +sv_pure 2 +z_difficulty hard -tickrate 100 -insecure -norestart -notrap" /dev/null
