---

# Installed by default by Arch Linux ARM
- user: name=alarm state=absent force=yes
- service: name=systemd-networkd enabled=no

# texinfo is needed by guile->gdb, but it should be installed as dep
- command: pacman -D --asdeps texinfo
